### ISSUE TITLE
[Interview] css实现三角形

### ISSUE THREAD

**Issue by xqiqi** [xqiqi/xqiqi#4]
``` css
/* 向上 */
#triangle-up {
    width: 0;
    height: 0;
    border-left: 50px solid transparent;
    border-right: 50px solid transparent;
    border-bottom: 100px solid red;
}

/* 向下 */
#triangle-down {
    width: 0;
    height: 0;
    border-left: 50px solid transparent;
    border-right: 50px solid transparent;
    border-top: 100px solid red;
}

/* 直角（左上角） */
#triangle-topleft {
    width: 0;
    height: 0;
    border-width: 100px;
    border-style: solid;
    border-color: red transparent transparent red;
}

/* 其余三角形可以此类推 */
```
